### ISSUE TITLE
Can't even make portal

### ISSUE THREAD

**Issue by leafyzefoowy** [MeowMC/PortalGun#21]
Whenever i left or right click, i can't make a portal, even shift then click still make the gun mine instead of make a portal

**Comment by MeowMC** [comment]
May you provide a video of you attempting? That will be the most useful in this case. Thanks!

**Comment by EpicScarDev** [comment]
I have the same issue, and although I dont have video footage, this error might help:

`[15:00:04] [Server thread/ERROR]: Failed to process task com.qouteall.immersive_portals.my_util.MyTaskList$2@38cfbba6
[15:00:04] [Server thread/INFO]: [STDERR]: java.lang.NullPointerException: entity not yet tracked
[15:00:04] [Server thread/INFO]: [STDERR]: 	at java.util.Objects.requireNonNull(Objects.java:290)
[15:00:04] [Server thread/INFO]: [STDERR]: 	at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
[15:00:04] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3898.resendSpawnPacketToTrackers(class_3898.java:2303)
[15:00:04] [Server thread/INFO]: [STDERR]: 	at com.qouteall.immersive_portals.portal.Portal.reloadAndSyncToClient(Portal.java:268)
[15:00:04] [Server thread/INFO]: [STDERR]: 	at tk.meowmc.portalgun.items.PortalGunItem.lambda$use$1(PortalGunItem.java:391)
[15:00:04] [Server thread/INFO]: [STDERR]: 	at tk.meowmc.portalgun.items.PortalGunItem$$Lambda$7662/1917765461.run(Unknown Source)
[15:00:04] [Server thread/INFO]: [STDERR]: 	at com.qouteall.immersive_portals.my_util.MyTaskList.lambda$oneShotTask$1(MyTaskList.java:52)
[15:00:04] [Server thread/INFO]: [STDERR]: 	at com.qouteall.immersive_portals.my_util.MyTaskList$$Lambda$7617/131335958.runAndGetIsFinished(Unknown Source)
[15:00:04] [Server thread/INFO]: [STDERR]: 	at com.qouteall.immersive_portals.my_util.MyTaskList$2.runAndGetIsFinished(MyTaskList.java:92)
[15:00:04] [Server thread/INFO]: [STDERR]: 	at com.qouteall.immersive_portals.my_util.MyTaskList.lambda$processTasks$0(MyTaskList.java:35)
[15:00:04] [Server thread/INFO]: [STDERR]: 	at com.qouteall.immersive_portals.my_util.MyTaskList$$Lambda$4350/124435180.test(Unknown Source)
[15:00:04] [Server thread/INFO]: [STDERR]: 	at com.qouteall.immersive_portals.Helper.removeIf(Helper.java:523)
[15:00:04] [Server thread/INFO]: [STDERR]: 	at com.qouteall.immersive_portals.my_util.MyTaskList.processTasks(MyTaskList.java:33)
[15:00:04] [Server thread/INFO]: [STDERR]: 	at com.qouteall.immersive_portals.ModMain$$Lambda$2516/1676939472.run(Unknown Source)
[15:00:04] [Server thread/INFO]: [STDERR]: 	at com.qouteall.immersive_portals.my_util.Signal.lambda$emit$0(Signal.java:18)
[15:00:04] [Server thread/INFO]: [STDERR]: 	at com.qouteall.immersive_portals.my_util.Signal$$Lambda$6225/791688170.accept(Unknown Source)
[15:00:04] [Server thread/INFO]: [STDERR]: 	at java.util.ArrayList.forEach(ArrayList.java:1249)
[15:00:04] [Server thread/INFO]: [STDERR]: 	at com.qouteall.immersive_portals.my_util.Signal.emit(Signal.java:18)
[15:00:04] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.handler$zin000$onServerTick(MinecraftServer.java:2253)
[15:00:04] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:894)
[15:00:04] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
[15:00:04] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1132.method_3748(class_1132.java:91)
[15:00:04] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
[15:00:04] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
[15:00:04] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer$$Lambda$6260/2090612030.run(Unknown Source)
[15:00:04] [Server thread/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:745)`

**Comment by Somiona** [comment]
I have the same issue happening, I have both Immersive Portals 1.2.5 and your mod installed. 
```
[12:58:56] [Server thread/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2382.method_10263()" because "upright" is null
[12:58:56] [Server thread/INFO]: [STDERR]: 	at tk.meowmc.portalgun.misc.PortalMethods.calcPortalPos(PortalMethods.java:62)
[12:58:56] [Server thread/INFO]: [STDERR]: 	at tk.meowmc.portalgun.misc.PortalMethods.Settings1(PortalMethods.java:88)
[12:58:56] [Server thread/INFO]: [STDERR]: 	at tk.meowmc.portalgun.misc.PortalMethods.portal2Methods(PortalMethods.java:193)
[12:58:56] [Server thread/INFO]: [STDERR]: 	at tk.meowmc.portalgun.items.PortalGunItem.lambda$use$1(PortalGunItem.java:369)
[12:58:56] [Server thread/INFO]: [STDERR]: 	at qouteall.q_misc_util.my_util.MyTaskList.lambda$oneShotTask$1(MyTaskList.java:52)
[12:58:56] [Server thread/INFO]: [STDERR]: 	at qouteall.q_misc_util.my_util.MyTaskList$2.runAndGetIsFinished(MyTaskList.java:92)
[12:58:56] [Server thread/INFO]: [STDERR]: 	at qouteall.q_misc_util.my_util.MyTaskList.lambda$processTasks$0(MyTaskList.java:35)
[12:58:56] [Server thread/INFO]: [STDERR]: 	at qouteall.q_misc_util.Helper.removeIf(Helper.java:502)
[12:58:56] [Server thread/INFO]: [STDERR]: 	at qouteall.q_misc_util.my_util.MyTaskList.processTasks(MyTaskList.java:33)
[12:58:56] [Server thread/INFO]: [STDERR]: 	at qouteall.q_misc_util.my_util.Signal.lambda$emit$0(Signal.java:18)
[12:58:56] [Server thread/INFO]: [STDERR]: 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[12:58:56] [Server thread/INFO]: [STDERR]: 	at qouteall.q_misc_util.my_util.Signal.emit(Signal.java:18)
[12:58:56] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.handler$fcj000$onServerTick(MinecraftServer.java:9784)
[12:58:56] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:902)
[12:58:56] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
[12:58:56] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1132.method_3748(class_1132.java:99)
[12:58:56] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.handler$cfk000$modifiedRunLoop(MinecraftServer.java:6356)
[12:58:56] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:663)
[12:58:56] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
[12:58:56] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[12:59:11] [Bewitchment Contributor List Loader Thread/INFO]: [STDOUT]: Failed to load contributor list. Contributor horns will not be rendered.
```

A possible workaround for me is to remove bundled `META-INF\jars\imm_ptl_core-1.18-SNAPSHOT.jar` and corresponding entry in `fabric.mod.json`

**Comment by froyo4u** [comment]
Yes I'm aware I advise just not using the 1.18 version as it wasn't tested cuz I'm an idiot and I just wanted to rush it out so people would stop complaining
