### ISSUE TITLE
crash with Iris + Sodium

### ISSUE THREAD

**Issue by Lolothepro** [MeowMC/PortalGun#24]
The bug this product as soon as we place a portal

```
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 20/11/2021 18:07
Description: Unexpected error

java.lang.NoSuchMethodError: 'me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.getInstance()'
	at qouteall.imm_ptl.core.compat.sodium_compatibility.SodiumInterface$OnSodiumPresent.switchContextWithCurrentWorldRenderer(SodiumInterface.java:56)
	at qouteall.imm_ptl.core.render.MyGameRenderer.switchAndRenderTheWorld(MyGameRenderer.java:179)
	at qouteall.imm_ptl.core.render.MyGameRenderer.renderWorldNew(MyGameRenderer.java:75)
	at qouteall.imm_ptl.core.compat.iris_compatibility.IrisPortalRenderer.invokeWorldRendering(IrisPortalRenderer.java:294)
	at qouteall.imm_ptl.core.render.PortalRenderer.renderPortalContent(PortalRenderer.java:196)
	at qouteall.imm_ptl.core.compat.iris_compatibility.IrisPortalRenderer.doRenderPortal(IrisPortalRenderer.java:231)
	at qouteall.imm_ptl.core.render.PortalRenderer.renderPortals(PortalRenderer.java:111)
	at qouteall.imm_ptl.core.compat.iris_compatibility.IrisPortalRenderer.onBeforeHandRendering(IrisPortalRenderer.java:142)
	at net.minecraft.class_757.handler$zim000$onRightBeforeHandRendering(class_757.java:2644)
	at net.minecraft.class_757.method_3188(class_757.java:1026)
	at net.minecraft.class_757.redirect$zim000$redirectRenderingWorld(class_757.java:2622)
	at net.minecraft.class_757.method_3192(class_757.java:810)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at qouteall.imm_ptl.core.compat.sodium_compatibility.SodiumInterface$OnSodiumPresent.switchContextWithCurrentWorldRenderer(SodiumInterface.java:56)
	at qouteall.imm_ptl.core.render.MyGameRenderer.switchAndRenderTheWorld(MyGameRenderer.java:179)
	at qouteall.imm_ptl.core.render.MyGameRenderer.renderWorldNew(MyGameRenderer.java:75)
	at qouteall.imm_ptl.core.compat.iris_compatibility.IrisPortalRenderer.invokeWorldRendering(IrisPortalRenderer.java:294)
	at qouteall.imm_ptl.core.render.PortalRenderer.renderPortalContent(PortalRenderer.java:196)
	at qouteall.imm_ptl.core.compat.iris_compatibility.IrisPortalRenderer.doRenderPortal(IrisPortalRenderer.java:231)
	at qouteall.imm_ptl.core.render.PortalRenderer.renderPortals(PortalRenderer.java:111)
	at qouteall.imm_ptl.core.compat.iris_compatibility.IrisPortalRenderer.onBeforeHandRendering(IrisPortalRenderer.java:142)
	at net.minecraft.class_757.handler$zim000$onRightBeforeHandRendering(class_757.java:2644)
	at net.minecraft.class_757.method_3188(class_757.java:1026)
	at net.minecraft.class_757.redirect$zim000$redirectRenderingWorld(class_757.java:2622)

-- Affected level --
Details:
	All players: 1 total; [class_746['Lolothepro29'/162, l='ClientWorld minecraft:overworld', x=-272.44, y=67.07, z=-246.31]]
	Chunk stats: Client Chunks (ImmPtl) 801
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 869 game time, 869 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, PureBDcraft 128x MC117.zip

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64) version 5.14.0-19.2-liquorix-amd64
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1357416880 bytes (1294 MiB) / 3019898880 bytes (2880 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 1600 Six-Core Processor
	Identifier: AuthenticAMD Family 23 Model 1 Stepping 1
	Microarchitecture: Zen
	Frequency (GHz): 3,20
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: GP104 [GeForce GTX 1070]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288,00
	Graphics card #0 deviceId: 0x1b81
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 7873,82
	Virtual memory used (MB): 8383,98
	Swap memory total (MB): 0,00
	Swap memory used (MB): 0,00
	JVM Flags: 8 total; -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v5 5.0.38
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		fabric: Fabric API 0.42.1+1.17
		fabric-api-base: Fabric API Base 0.4.0+5847535018
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+5847535018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+5847535018
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+5847535018
		fabric-command-api-v1: Fabric Command API (v1) 1.1.4+5847535018
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+5847535018
		fabric-containers-v0: Fabric Containers (v0) 0.1.13+5847535018
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.1+5847535018
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+5847535018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.13+5847535018
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.1+5847535018
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.11+5847535018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+5847535018
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+5847535018
		fabric-item-api-v1: Fabric Item API (v1) 1.2.5+5847535018
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+5847535018
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+5847535018
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.3+5847535018
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.5+5847535018
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+5847535018
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.2+6d0fac4218
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.5+6d0fac4218
		fabric-models-v0: Fabric Models (v0) 0.3.1+5847535018
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+5847535018
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+5847535018
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+5847535018
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.11+6d0fac4218
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.5+6d0fac4218
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+5847535018
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.13+5847535018
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+5847535018
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.9+5847535018
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.6+6d0fac4218
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+5847535018
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.1+6d0fac4218
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.7+6d0fac4218
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.1+6d0fac4218
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.9+5847535018
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.5+5847535018
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+5847535018
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.14+5847535018
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.2+5847535018
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+5847535018
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.1+eb76084f18
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.1+6d0fac4218
		fabricloader: Fabric Loader 0.11.7
		geckolib3: Geckolib 3.0.29
		imm_ptl_core: Immersive Portals Core 0.20
		iris: Iris 1.1.2+build.9
		java: OpenJDK 64-Bit Server VM 16
		minecraft: Minecraft 1.17.1
		portalgun: Portal Gun 2.0.0
		q_misc_util: A Miscellaneous Utility Library from qouteall 0.20
		sodium: Sodium 0.3.2+IRIS2-build.9
		treefax: TreeFax 1.3.0
		treefelling: Treefelling 1.0.0
	Launched Version: fabric-loader-0.11.7-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1070/PCIe/SSE2 GL version 3.2.0 NVIDIA 495.44, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/PureBDcraft 128x MC117.zip
	Current Language: Français (France)
	CPU: 12x AMD Ryzen 5 1600 Six-Core Processor
	Player Count: 1 / 8; [class_3222['Lolothepro29'/162, l='ServerWorld minecraft:overworld Moremods', x=-272.56, y=67.07, z=-255.70]]
	Data Packs: vanilla, Fabric Mods
```

**Comment by NhProGamer** [comment]
logical because immersive portals is not compatible with sodium (iris)
look at the bottom of the mod's page

**Comment by Lolothepro** [comment]
Iris is compatible with Immersive portal
Sodium is compatible with Immersive portal

**Comment by NhProGamer** [comment]
![fghdfgh](https://user-images.githubusercontent.com/44909803/147847606-560c66cb-30f8-41ce-9ae4-021125c589ed.PNG)

**Comment by Lolothepro** [comment]
The problem with PortalGun is that it uses an older version of Immersive Portal
